### PR TITLE
Ab#111714 add versioning information to dashboard application

### PR DESCRIPTION
**Pull request by tc-chris**

### CODE REVIEW

**Review by AlexandreSanscartier — COMMENTED** [review]
Did we implement anything for automatically changing the version when we publish on DevOps? Is it possible or do we have to change it manually every time?

**Comment by tc-chris** [comment]
> Did we implement anything for automatically changing the version when we publish on DevOps? Is it possible or do we have to change it manually every time?

It looks like you are able to increment the version number, but you can't get the version in code.

**Comment by AlexandreSanscartier** [comment]
> > Did we implement anything for automatically changing the version when we publish on DevOps? Is it possible or do we have to change it manually every time?
> 
> It looks like you are able to increment the version number, but you can't get the version in code.

I believe VR has something in their settings file to generate the versioning on DevOps and use that in their code.

**Comment by tc-chris** [comment]
> > > Did we implement anything for automatically changing the version when we publish on DevOps? Is it possible or do we have to change it manually every time?
> > 
> > 
> > It looks like you are able to increment the version number, but you can't get the version in code.
> 
> I believe VR has something in their settings file to generate the versioning on DevOps and use that in their code.

Should we make a PBI for this and have these questions in that PBI? As this PBI didn't require automatic versioning.

**Pull request merged**
