### PR TITLE
AB#46321 Add Architecture Diagrams to the 'docs' Folder.

### PR DESCRIPTION
**Pull request by TCPrimedPaul**
List of diagrams added:
- Infrastructure diagram
- Domain model diagram
- Solution architecture diagram

_Note:_ Bear in mind that these diagrams are meant to represent current state only.

### CODE REVIEW

**Review by tc-tibo — COMMENTED** [review]
For the Solution Architecture Diagram

image

Was there a tool in VS Enterprise that @tropical-turtle showed us that generated these diagrams? We could use that tool to ensure our solution matches to this diagram (or vice versa).

**Review by tc-tibo — DISMISSED** [review]
I really like everything you've done @TCPrimedPaul

**Comment by tc-tibo** [comment]
@TCPrimedPaul , can you merge from Master since you have this PR open? It's just to grab the other docs. I added them there originally to experiment with GitHub Pages.

**Comment by TCPrimedPaul** [comment]
@tc-tibo I believe the tool in VS you are referring to is _[Code Map](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2019)_.

**Comment by tc-tibo** [comment]
Sorry @TCPrimedPaul, I think I may have messed up by not being clear.

I think you were correct in having it in `develop`. My intent was to ask you to merge from `master` into `develop`, so that all the documentation would appear in the /docs folder in `develop`.

**Review by tc-tibo — APPROVED** [review]
Pls ignore the request about merging from `master` branch. This PR is excellent and shouldn't be blocked by a separate request. I will open a separate PR for that.

**Comment by tc-tibo** [comment]
> @tc-tibo I believe the tool in VS you are referring to is _[Code Map](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2019)_.

Yes, that's the one. Thanks @TCPrimedPaul

**Pull request merged**
