### PR TITLE
Feature/ab#49323 new renewal cert

### PR DESCRIPTION
**Pull request by AlexandreSanscartier**
Added text to the email to indicate what type of submission it is (renewal / new)

### CODE REVIEW

**Review by tc-chris — CHANGES_REQUESTED** [review]
The table in English is french and vice versa

**Comment by AlexandreSanscartier** [comment]
> The table in English is french and vice versa

Fixed thanks for pointing it out. It seemed to be ok in the French email.

**Review by tc-chris — APPROVED** [review]
Works now

**Review by tc-chris — APPROVED** [review]

**Review by TCPrimedPaul — APPROVED** [review]
Excellent work with the many refactorings!!! I wish I could spend more time admiring.
I tested locally both english/french, everything looked good.

**Pull request merged**
